__step 1 -Import Pandas as pd,
         Import Numpy as np,
         Read data and assign variable movies__

In [1]:
import pandas as pd
import numpy as np
movies = pd.read_csv('movie_dataset.csv')

__Step 2 - Check the rows and columns of first 5 values__

In [2]:
movies.head(5)

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

__Step 3 - Check overall Information of the data set__

In [3]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   index                 4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4775 non-null   object 
 3   homepage              1712 non-null   object 
 4   id                    4803 non-null   int64  
 5   keywords              4391 non-null   object 
 6   original_language     4803 non-null   object 
 7   original_title        4803 non-null   object 
 8   overview              4800 non-null   object 
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object 
 11  production_countries  4803 non-null   object 
 12  release_date          4802 non-null   object 
 13  revenue               4803 non-null   int64  
 14  runtime               4801 non-null   float64
 15  spoken_languages     

__Step 4 - Select the features needed and put them in Features Variable__

In [4]:
features =['keywords','cast','genres','director']

**Step 5 - Fill all the NA values of Features selected**

In [5]:
for feature in features:
    movies[feature] = movies[feature].fillna(' ') 

**Step 6 - Check if the Na Values for features are filled properly**

In [6]:
movies.isna().sum()

index                      0
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                       0
crew                       0
director                   0
dtype: int64

**Step 7 - Define a Function to combine all the Features in one column**

In [7]:
def combine(rows):
    return str(rows['keywords']) + " " + str(rows['cast']) + " " + str(rows['director']) + " " + str(rows['genres'])

**Step 8 - Introduce new column called as 'combine features' which will have all the features in it**

In [8]:
movies['combine features'] = movies.apply(combine , axis = 1)

**Step 9 - Check If the column is added properly.**

In [9]:
movies.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director',
       'combine features'],
      dtype='object')

**Step 10 - Google how to do words counting using scikit learn and import Class for the same**

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

**Step 11 - Assign variable cv for the class imported**

In [11]:
cv = CountVectorizer()

**Step 12 - Use respective method from CountVectorizer class to perform word counting.**

In [12]:
count_matrix = cv.fit_transform(movies['combine features'])

**Step 13 - CHeck If the word counting is done**

In [13]:
print(count_matrix.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


**Step 14 - Find a way to measure distance between vectors using cosine similarity.**

In [14]:
from sklearn.metrics.pairwise import cosine_similarity

**Step 15 - Store the Value in variable similarity_score**

In [15]:
similarity_score = cosine_similarity(count_matrix)

**Step 16 - Check for similarity scores**

In [16]:
print(similarity_score)

[[1.         0.10540926 0.12038585 ... 0.         0.         0.        ]
 [0.10540926 1.         0.0761387  ... 0.03651484 0.         0.        ]
 [0.12038585 0.0761387  1.         ... 0.         0.11145564 0.        ]
 ...
 [0.         0.03651484 0.         ... 1.         0.         0.04264014]
 [0.         0.         0.11145564 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.04264014 0.         1.        ]]


**Step 17 - Define Helper FUnctions to get title from index and vice versa**

In [17]:
def get_title_from_index(index):
    return movies[movies.index == index]['title'].values[0]
def get_index_from_title(title):
    return movies[movies.title == title]['index'].values[0]

**Step 19 - Assigine Variable for Users movie, Get the index of movie, Enumerate Similarity Scores**

In [18]:
movie_user_likes = 'Harry Potter and the Half-Blood Prince'
movie_index = get_index_from_title(movie_user_likes)
similar_movies = list(enumerate(similarity_score[movie_index])) 

**Step 20 - Sort the tuples in reverse order**

In [19]:
sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)[1:]

**Step 21 - Use for loop to get the names of first 5 similar movies**

In [20]:
i=0
print('Top 5 similar movies to “+movie_user_likes+” are:\n')
for element in sorted_similar_movies:
    print(get_title_from_index(element[0]))
    i=i+1
    if i>5:
        break

Top 5 similar movies to “+movie_user_likes+” are:

Harry Potter and the Order of the Phoenix
Harry Potter and the Goblet of Fire
Harry Potter and the Philosopher's Stone
Harry Potter and the Prisoner of Azkaban
Harry Potter and the Chamber of Secrets
Treasure Planet


 # <font color=Orange> Congratulations!! You Have Just Completed Your First Project</font>